name: radarr

services:
  radarr:
    image: ghcr.io/hotio/radarr:release-${RADARR_VERSION}
    container_name: radarr
    volumes:
      - radarr_config:/config:rw
      - ~/Videos/movies:/movies:rw
      - ~/Downloads:/data/downloads:rw
    ports:
      - '127.0.0.1:7878:7878'
    networks:
      - backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^release-\d+\.\d+\.\d+.\d+$$
      - traefik.enable=true
      - traefik.http.routers.radarr-radarr.rule=Host(`radarr.dhjensen.tech`)

networks:
  backend:
    external: true
    driver: bridge

volumes:
  radarr_config:
